### ISSUE TITLE
[FeatureRequest] rpcuser & rpcpassword in sentinel.conf

### ISSUE THREAD

**Issue by MrDefacto** [nmarley/sentinel#18]
Hi,

When using rpcauth (instead of rpcuser and rpcpassword) in dash.conf (modern) then sentinel can't read password. I think that password to rpc should be defined in sentinel.conf - not readed from dash.conf.

Second feature that except rpcport there also should be readed definition of rpchost. These two variables also should be read from sentinel.conf and not from dash.conf.

Best regards,
D

**Comment by nmarley** [comment]
Great ideas, thanks for reporting!

Fully agree on the rpcauth change, opened #19 for that specifically.

I understand your point about putting authentication in sentinel.conf as it more loosely couples the systems, which is usually a good thing. However, in this case, a tighter coupling is desired as one of Sentinel's core design principles. Sentinel is intentionally designed to run only alongside a running DashCore node on the same host.

Also, by keeping the authentication in `dash.conf`, it mirrors the same access controls as dash-cli/DashCore itself, and does not add another point of failure (authentication mis-match) and redundant information (since auth info is already in `dash.conf` and it's required to run Sentinel locally).

**Comment by MrDefacto** [comment]
I understand... but still... it uses only rpc (not reading/accessing blockchaing or *.dat files directly) and for few reasons it can by run even on different host :-) i understand Your point of view in design but still... ;-)

**Comment by nmarley** [comment]
Closing in lieu of #19 and other configuration is working by-design.
