### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by yanikkoval** [nmarley/sentinel#24]
I noticed that this project is using Python 2. Is there are some important reasons behind?

I would suggest to use Python3 instead, or at least write Python3 compatible code (__future__). So it will be much easier to migrate later on.

**Comment by nmarley** [comment]
> I noticed that this project is using Python 2. Is there are some important reasons behind?

It started as Python 2 and most default Python installations are still Python 2. It supports Python 3 since commit d7fe903d9e28c3737d61f2ed2e626316390b07b4. The code should work for both Python 2 and 3.

As the README advises operators to use virtualenv to run Sentinel, either Python 2 or 3 can be selected by using the `-p` flag with virtualenv.
