### ISSUE TITLE
change default values in sentinel.conf to mainnet

### ISSUE THREAD

**Issue by nmarley** [nmarley/sentinel#7]
Will change this before mainnet release.

**Comment by taw00** [comment]
Better yet, have dash.conf's setting for the override it. I suppose since dash.conf is set to testnet, or not testnet, that can be similarly ambiguous?

sentinel.conf (testnet), dash.conf (unset) -- we are testnet
sentinel.conf (unset), dash.conf (testnet) -- we are testnet
sentinel.conf (unset), dash.conf (unset) -- we are mainnet

Isn't this how it is supposed to work? Just checking.

**Comment by nmarley** [comment]
Fixed as of 4374690b37102369ae192be48f9d1448a4720158
